### ISSUE TITLE
create the Hero Section including responsiveness

### ISSUE THREAD

**Issue by victorchrollo14** [victorchrollo14/mernEcommerce#14]

**Comment by HarshDeep61034** [comment]
plz elaborate more idk what a hero section is!

**Comment by victorchrollo14** [comment]
Hero Section.
![Screenshot from 2023-08-04 09-54-08](https://github.com/victorchrollo14/mernEcommerce/assets/89346667/37bd53ca-d999-4f3c-b1fe-d27c17bb1654)
![Screenshot from 2023-08-04 09-56-13](https://github.com/victorchrollo14/mernEcommerce/assets/89346667/81a472e7-b4d0-4edc-bd93-57600f511436)

**Comment by victorchrollo14** [comment]
Done
