### ISSUE TITLE
 Add the Brands Section.

### ISSUE THREAD

**Issue by victorchrollo14** [victorchrollo14/mernEcommerce#15]

**Comment by victorchrollo14** [comment]
brands section look into the design.

![Screenshot from 2023-08-04 09-58-25](https://github.com/victorchrollo14/mernEcommerce/assets/89346667/51358f73-14e9-460a-a712-f4035bf25215)
![Screenshot from 2023-08-04 09-59-37](https://github.com/victorchrollo14/mernEcommerce/assets/89346667/3cf74fc9-9d36-4ec9-9817-ffb629ad8b23)

**Comment by Monilprajapati** [comment]
Done #36
