### ISSUE TITLE
create the Cart Page for both mobile and desktop version.

### ISSUE THREAD

**Issue by victorchrollo14** [victorchrollo14/mernEcommerce#37]
![CArt page](https://github.com/victorchrollo14/mernEcommerce/assets/89346667/d6950ab9-7247-4c13-ae1b-344fe61f6648)

**Comment by Monilprajapati** [comment]
I am working on it

**Comment by victorchrollo14** [comment]
> I am working on it

gambare gambare

**Comment by Monilprajapati** [comment]
Done with this issue PR #41
