### ISSUE TITLE
Create Client side routing for shop page and product page.

### ISSUE THREAD

**Issue by victorchrollo14** [victorchrollo14/mernEcommerce#40]
## Tasks

*  create new routes for each product when we click on different products in shop page.
*  example: /shop/shirts , /shop/bottoms, /shop/knits. Etc
*  Add a link on each product in shop page such that, it directs to the product page with the corresponding product data. Eg: /shop/product-name1  /shop/product-name2 , /shop/product-name3.

## I think this can be achieved with something called as dynamic routing.

**Comment by sahith29s** [comment]
Hey can I contribute in this ?

**Comment by victorchrollo14** [comment]
Done
