### ISSUE TITLE
[Fix] : Fix the data fetching Issue in Deployed Link

### ISSUE THREAD

**Issue by Monilprajapati** [victorchrollo14/mernEcommerce#49]
Data of products has not been fetched.
@victorchrollo14

**Comment by victorchrollo14** [comment]
I think we can't fix it, the only way to fix it is to create a serverless function in vercel to fetch the data, something similar to what you've do in express.

**Comment by Monilprajapati** [comment]
> I think we can't fix it, the only way to fix it is to create a serverless function in vercel to fetch the data, something similar to what you've do in express.

Okkkk

**Comment by victorchrollo14** [comment]
closing this issue, since we won't fix this rather deploy the backend on azure and fetch the images from there to the site hosted on vercel.
