### ISSUE TITLE
Build the Item page or the product page.

### ISSUE THREAD

**Issue by victorchrollo14** [victorchrollo14/mernEcommerce#5]
create the item page including responsiveness
![Product Page](https://github.com/victorchrollo14/mernEcommerce/assets/89346667/5f7ff1b5-b736-4234-a962-e3e7a6d9d312)

**Comment by HarshDeep61034** [comment]
You mean the item component

**Comment by HarshDeep61034** [comment]
I'm working on this 👍

**Comment by HarshDeep61034** [comment]
I mistakenly closed it but then reopened it.

**Comment by victorchrollo14** [comment]
> You mean the item component

A page where you can view a single product with all the details such price, quantity and  add to cart etc. I think we should call it product page and the page where all products are listed as shop page.

got some wireframes, I can design it a bit faster now.
https://www.figma.com/file/figjD5PRyaAJ5ffTFVOMDN/Ecommerce-Site-Mern?type=design&node-id=0-1&mode=design&t=7yAuU5cH2GLbHRNT-0

**Comment by HarshDeep61034** [comment]
@victorchrollo14 Product page is completed, in issue #4  Do you mean product card ?

**Comment by Monilprajapati** [comment]
Currently I am working on this Issu

**Comment by Monilprajapati** [comment]
Ok so for now i think we should close this issue @victorchrollo14

**Comment by victorchrollo14** [comment]
Done
