### ISSUE TITLE
[Feature] : Add Sorting Functionality in Shop Page

### ISSUE THREAD

**Issue by Monilprajapati** [victorchrollo14/mernEcommerce#50]
Add sorting functionality in Shop page 

- Sort according to
     - Price

Preview : 
![image](https://github.com/victorchrollo14/mernEcommerce/assets/99136041/24f1e2ac-9cbe-4469-aa1f-0e14b780438c)

**Comment by victorchrollo14** [comment]
Just put the logic part on hold for now. 
Go ahead and create the component for this one plus the one you see towards it's left corner in the design.

**Comment by victorchrollo14** [comment]
I'm thinking of changing the logic for productContext such that we will provide the category state within the productContextProvider this way we will be able to change the product categories that are shown in shop page from differnt places like mobile navigation as well the component to switch between products.

**Comment by victorchrollo14** [comment]
fixed
